name: CI

on:
  push: 
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checout repository
        uses: actions/checkout@v5

      - name: run a one-line sctipt
        run: echo Hello World!


      - name: run a multi-line sctipt 
        run: |
          echo add other actions 
          echo to build and test your project. 
